spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit-v2?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#
#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml   # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  type-aliases-package: com.example.demosp.pojo  # 注意：对应实体类的路径
#  #开启驼峰转换
#  configuration:
#    mapUnderscoreToCamelCase: true